/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BitcoinTransaction
 */
export interface BitcoinTransaction {
  /**
   * The PSBT bytes, base64-encoded
   * @type {string}
   * @memberof BitcoinTransaction
   */
  bytes: string;
  /**
   *
   * @type {string}
   * @memberof BitcoinTransaction
   */
  kind: BitcoinTransactionKindEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BitcoinTransactionKindEnum {
  psbt = "PSBT",
}
