/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyPresetOneOf } from "./cel-policy-preset-one-of";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyPresetOneOf1 } from "./cel-policy-preset-one-of1";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyPresetOneOf2 } from "./cel-policy-preset-one-of2";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyPresetOneOf3 } from "./cel-policy-preset-one-of3";
// May contain unused imports in some cases
// @ts-ignore
import type { UsdLimitSettings } from "./usd-limit-settings";

/**
 * @type CelPolicyPreset
 * @export
 */
export type CelPolicyPreset =
  | CelPolicyPresetOneOf
  | CelPolicyPresetOneOf1
  | CelPolicyPresetOneOf2
  | CelPolicyPresetOneOf3;
