/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A preset that legacy User role within Org is converted to, replicating old RBAC logic.
 * @export
 * @interface CelPolicyPresetOneOf3
 */
export interface CelPolicyPresetOneOf3 {
  /**
   *
   * @type {string}
   * @memberof CelPolicyPresetOneOf3
   */
  preset: CelPolicyPresetOneOf3PresetEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CelPolicyPresetOneOf3PresetEnum {
  legacyUserRole = "LEGACY_USER_ROLE",
}
