/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyOutcome } from "./cel-policy-outcome";

/**
 *
 * @export
 * @interface CelPolicyRule
 */
export interface CelPolicyRule {
  /**
   *
   * @type {string}
   * @memberof CelPolicyRule
   */
  comment: string;
  /**
   *
   * @type {string}
   * @memberof CelPolicyRule
   */
  expression: string;
  /**
   *
   * @type {CelPolicyOutcome}
   * @memberof CelPolicyRule
   */
  outcome: CelPolicyOutcome;
}
