/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PartialKmsUser } from "./partial-kms-user";

/**
 *
 * @export
 * @interface CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
  /**
   *
   * @type {string}
   * @memberof CreateOrganizationRequest
   */
  organizationName: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateOrganizationRequest
   */
  tags?: Array<string>;
  /**
   *
   * @type {Array<PartialKmsUser>}
   * @memberof CreateOrganizationRequest
   */
  users: Array<PartialKmsUser>;
}
