/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CreateOrganizationRequest } from "./create-organization-request";

/**
 *
 * @export
 * @interface CreateOrganization
 */
export interface CreateOrganization {
  /**
   *
   * @type {string}
   * @memberof CreateOrganization
   */
  method: CreateOrganizationMethodEnum;
  /**
   *
   * @type {CreateOrganizationRequest}
   * @memberof CreateOrganization
   */
  params: CreateOrganizationRequest;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateOrganizationMethodEnum {
  createOrganization = "createOrganization",
}
