/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExternalDerivedAccount } from "./external-derived-account";
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalKeypairAccount } from "./external-keypair-account";
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalWalletAccountsOneOf } from "./external-wallet-accounts-one-of";
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalWalletAccountsOneOf1 } from "./external-wallet-accounts-one-of1";

/**
 * @type ExternalWalletAccounts
 * @export
 */
export type ExternalWalletAccounts = ExternalWalletAccountsOneOf | ExternalWalletAccountsOneOf1;
