/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CelFullPolicy } from "./cel-full-policy";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyConstant } from "./cel-policy-constant";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyPreset } from "./cel-policy-preset";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyRule } from "./cel-policy-rule";
// May contain unused imports in some cases
// @ts-ignore
import type { UsdLimitSettings } from "./usd-limit-settings";

/**
 * @type ExternalCelPolicy
 * Generic policy based on Common Expression Language (CEL) and a layer of JSON config on top of it: - allow/deny rules, each with a CEL expression - constants (values that can be used in the CEL expressions) - comments  Initially used by KMS transaction policies, but can be used in other places as well.
 * @export
 */
export type ExternalCelPolicy = CelFullPolicy | CelPolicyPreset;
