/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetAccountsRequest } from "./get-accounts-request";

/**
 *
 * @export
 * @interface GetAccounts
 */
export interface GetAccounts {
  /**
   *
   * @type {string}
   * @memberof GetAccounts
   */
  method: GetAccountsMethodEnum;
  /**
   *
   * @type {GetAccountsRequest}
   * @memberof GetAccounts
   */
  params: GetAccountsRequest;
}

/**
 * @export
 * @enum {string}
 */
export enum GetAccountsMethodEnum {
  getAccounts = "getAccounts",
}
