/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetWalletWithTagRequest } from "./get-wallet-with-tag-request";

/**
 *
 * @export
 * @interface GetWalletWithTag
 */
export interface GetWalletWithTag {
  /**
   *
   * @type {string}
   * @memberof GetWalletWithTag
   */
  method: GetWalletWithTagMethodEnum;
  /**
   *
   * @type {GetWalletWithTagRequest}
   * @memberof GetWalletWithTag
   */
  params: GetWalletWithTagRequest;
}

/**
 * @export
 * @enum {string}
 */
export enum GetWalletWithTagMethodEnum {
  getWalletWithTag = "getWalletWithTag",
}
