/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AddressFormat } from "./address-format";
// May contain unused imports in some cases
// @ts-ignore
import type { DerivationInfoSchema } from "./derivation-info-schema";
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalCurve } from "./external-curve";
// May contain unused imports in some cases
// @ts-ignore
import type { WalletParameters } from "./wallet-parameters";

/**
 * @type GetOrCreateWalletWithTagRequest
 * @export
 */
export type GetOrCreateWalletWithTagRequest = WalletParameters;
