/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetOrganizationRequest } from "./get-organization-request";

/**
 *
 * @export
 * @interface GetOrganization
 */
export interface GetOrganization {
  /**
   *
   * @type {string}
   * @memberof GetOrganization
   */
  method: GetOrganizationMethodEnum;
  /**
   *
   * @type {GetOrganizationRequest}
   * @memberof GetOrganization
   */
  params: GetOrganizationRequest;
}

/**
 * @export
 * @enum {string}
 */
export enum GetOrganizationMethodEnum {
  getOrganization = "getOrganization",
}
