/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetPhantomOrganization
 */
export interface GetPhantomOrganization {
  /**
   *
   * @type {string}
   * @memberof GetPhantomOrganization
   */
  method: GetPhantomOrganizationMethodEnum;
  /**
   *
   * @type {object}
   * @memberof GetPhantomOrganization
   */
  params: object;
}

/**
 * @export
 * @enum {string}
 */
export enum GetPhantomOrganizationMethodEnum {
  getPhantomOrganization = "getPhantomOrganization",
}
