/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { InstructionValidationRuleOneOf } from "./instruction-validation-rule-one-of";
// May contain unused imports in some cases
// @ts-ignore
import type { InstructionValidationRuleOneOf1 } from "./instruction-validation-rule-one-of1";
// May contain unused imports in some cases
// @ts-ignore
import type { InstructionValidationRuleOneOf2 } from "./instruction-validation-rule-one-of2";

/**
 * @type InstructionValidationRule
 * @export
 */
export type InstructionValidationRule =
  | InstructionValidationRuleOneOf
  | InstructionValidationRuleOneOf1
  | InstructionValidationRuleOneOf2;
