/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AddUserToOrganization } from "./add-user-to-organization";
// May contain unused imports in some cases
// @ts-ignore
import type { CompleteImportWallet } from "./complete-import-wallet";
// May contain unused imports in some cases
// @ts-ignore
import type { CreateAuthenticator } from "./create-authenticator";
// May contain unused imports in some cases
// @ts-ignore
import type { CreateOrganization } from "./create-organization";
// May contain unused imports in some cases
// @ts-ignore
import type { CreateWallet } from "./create-wallet";
// May contain unused imports in some cases
// @ts-ignore
import type { DeleteAuthenticator } from "./delete-authenticator";
// May contain unused imports in some cases
// @ts-ignore
import type { DeleteUserFromOrganization } from "./delete-user-from-organization";
// May contain unused imports in some cases
// @ts-ignore
import type { EthereumSignMessageAsPerEIP191 } from "./ethereum-sign-message-as-per-eip191";
// May contain unused imports in some cases
// @ts-ignore
import type { EthereumSignTypedDataAsPerEIP712 } from "./ethereum-sign-typed-data-as-per-eip712";
// May contain unused imports in some cases
// @ts-ignore
import type { ExportWallet } from "./export-wallet";
// May contain unused imports in some cases
// @ts-ignore
import type { GetAccounts } from "./get-accounts";
// May contain unused imports in some cases
// @ts-ignore
import type { GetOrCreatePhantomOrganization } from "./get-or-create-phantom-organization";
// May contain unused imports in some cases
// @ts-ignore
import type { GetOrCreateWalletWithTag } from "./get-or-create-wallet-with-tag";
// May contain unused imports in some cases
// @ts-ignore
import type { GetOrganization } from "./get-organization";
// May contain unused imports in some cases
// @ts-ignore
import type { GetOrganizationWallets } from "./get-organization-wallets";
// May contain unused imports in some cases
// @ts-ignore
import type { GetPhantomOrganization } from "./get-phantom-organization";
// May contain unused imports in some cases
// @ts-ignore
import type { GetWalletAccessGrants } from "./get-wallet-access-grants";
// May contain unused imports in some cases
// @ts-ignore
import type { GetWalletAccessGrantsRequest } from "./get-wallet-access-grants-request";
// May contain unused imports in some cases
// @ts-ignore
import type { GetWalletWithTag } from "./get-wallet-with-tag";
// May contain unused imports in some cases
// @ts-ignore
import type { GrantOrganizationAccess } from "./grant-organization-access";
// May contain unused imports in some cases
// @ts-ignore
import type { InitWalletImport } from "./init-wallet-import";
// May contain unused imports in some cases
// @ts-ignore
import type { RevokeOrganizationAccess } from "./revoke-organization-access";
// May contain unused imports in some cases
// @ts-ignore
import type { SignRawPayload } from "./sign-raw-payload";
// May contain unused imports in some cases
// @ts-ignore
import type { SignTransaction } from "./sign-transaction";
// May contain unused imports in some cases
// @ts-ignore
import type { SignUTF8Message } from "./sign-utf8-message";
// May contain unused imports in some cases
// @ts-ignore
import type { TransferOrganizationWallet } from "./transfer-organization-wallet";
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateAuthenticator } from "./update-authenticator";
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateUserInOrganization } from "./update-user-in-organization";

/**
 * @type KmsRpcRequestParams
 * @export
 */
export type KmsRpcRequestParams =
  | AddUserToOrganization
  | CompleteImportWallet
  | CreateAuthenticator
  | CreateOrganization
  | CreateWallet
  | DeleteAuthenticator
  | DeleteUserFromOrganization
  | EthereumSignMessageAsPerEIP191
  | EthereumSignTypedDataAsPerEIP712
  | ExportWallet
  | GetAccounts
  | GetOrCreatePhantomOrganization
  | GetOrCreateWalletWithTag
  | GetOrganization
  | GetOrganizationWallets
  | GetPhantomOrganization
  | GetWalletAccessGrants
  | GetWalletWithTag
  | GrantOrganizationAccess
  | InitWalletImport
  | RevokeOrganizationAccess
  | SignRawPayload
  | SignTransaction
  | SignUTF8Message
  | TransferOrganizationWallet
  | UpdateAuthenticator
  | UpdateUserInOrganization;
