/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { KmcRpcResponseV2Error } from "./kmc-rpc-response-v2-error";
// May contain unused imports in some cases
// @ts-ignore
import type { KmcRpcResponseV2ErrorDetails } from "./kmc-rpc-response-v2-error-details";
// May contain unused imports in some cases
// @ts-ignore
import type { KmcRpcResponseV2Result } from "./kmc-rpc-response-v2-result";
// May contain unused imports in some cases
// @ts-ignore
import type { KmsResult } from "./kms-result";

/**
 * @type KmsRpcResponseV2
 * @export
 */
export type KmsRpcResponseV2 = KmcRpcResponseV2Error | KmcRpcResponseV2Result;
