/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationRootAccessOneOf } from "./organization-root-access-one-of";
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationRootAccessOneOf1 } from "./organization-root-access-one-of1";
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationRootAccessOneOf2 } from "./organization-root-access-one-of2";

/**
 * @type OrganizationRootAccess
 * @export
 */
export type OrganizationRootAccess =
  | OrganizationRootAccessOneOf
  | OrganizationRootAccessOneOf1
  | OrganizationRootAccessOneOf2;
