/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationRootAccessOneOf1
 */
export interface OrganizationRootAccessOneOf1 {
  /**
   *
   * @type {number}
   * @memberof OrganizationRootAccessOneOf1
   */
  timestampMs: number;
  /**
   *
   * @type {string}
   * @memberof OrganizationRootAccessOneOf1
   */
  type: OrganizationRootAccessOneOf1TypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum OrganizationRootAccessOneOf1TypeEnum {
  afterTimestamp = "AFTER_TIMESTAMP",
}
