/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyConstant } from "./cel-policy-constant";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyRule } from "./cel-policy-rule";
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalCelPolicy } from "./external-cel-policy";
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationRootAccess } from "./organization-root-access";
// May contain unused imports in some cases
// @ts-ignore
import type { UsdLimitSettings } from "./usd-limit-settings";

/**
 * @type OrganizationPolicyV1
 * @export
 */
export type OrganizationPolicyV1 = ExternalCelPolicy;
