/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SignRawPayloadRequest } from "./sign-raw-payload-request";

/**
 *
 * @export
 * @interface SignRawPayload
 */
export interface SignRawPayload {
  /**
   *
   * @type {string}
   * @memberof SignRawPayload
   */
  method: SignRawPayloadMethodEnum;
  /**
   *
   * @type {SignRawPayloadRequest}
   * @memberof SignRawPayload
   */
  params: SignRawPayloadRequest;
}

/**
 * @export
 * @enum {string}
 */
export enum SignRawPayloadMethodEnum {
  signRawPayload = "signRawPayload",
}
