/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { InstructionMatcher } from "./instruction-matcher";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf } from "./signer-policy-rule-one-of";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf1 } from "./signer-policy-rule-one-of1";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf2 } from "./signer-policy-rule-one-of2";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf3 } from "./signer-policy-rule-one-of3";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf4 } from "./signer-policy-rule-one-of4";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf5 } from "./signer-policy-rule-one-of5";
// May contain unused imports in some cases
// @ts-ignore
import type { SignerPolicyRuleOneOf6 } from "./signer-policy-rule-one-of6";

/**
 * @type SignerPolicyRule
 * @export
 */
export type SignerPolicyRule =
  | SignerPolicyRuleOneOf
  | SignerPolicyRuleOneOf1
  | SignerPolicyRuleOneOf2
  | SignerPolicyRuleOneOf3
  | SignerPolicyRuleOneOf4
  | SignerPolicyRuleOneOf5
  | SignerPolicyRuleOneOf6;
