/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SignUtf8MessageRequest } from "./sign-utf8-message-request";

/**
 *
 * @export
 * @interface SignUTF8Message
 */
export interface SignUTF8Message {
  /**
   *
   * @type {string}
   * @memberof SignUTF8Message
   */
  method: SignUTF8MessageMethodEnum;
  /**
   *
   * @type {SignUtf8MessageRequest}
   * @memberof SignUTF8Message
   */
  params: SignUtf8MessageRequest;
}

/**
 * @export
 * @enum {string}
 */
export enum SignUTF8MessageMethodEnum {
  signUtf8Message = "signUtf8Message",
}
