/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SignerPolicyRuleOneOf3
 */
export interface SignerPolicyRuleOneOf3 {
  /**
   *
   * @type {string}
   * @memberof SignerPolicyRuleOneOf3
   */
  rule: SignerPolicyRuleOneOf3RuleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SignerPolicyRuleOneOf3RuleEnum {
  noAddressLookupTables = "NoAddressLookupTables",
}
