/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SignedSolanaTransaction
 */
export interface SignedSolanaTransaction {
  /**
   *
   * @type {string}
   * @memberof SignedSolanaTransaction
   */
  kind: SignedSolanaTransactionKindEnum;
  /**
   * Base64UrlSafeEncoded signature, if applicable
   * @type {string}
   * @memberof SignedSolanaTransaction
   */
  signature: string;
  /**
   *
   * @type {string}
   * @memberof SignedSolanaTransaction
   */
  transaction: string;
}

/**
 * @export
 * @enum {string}
 */
export enum SignedSolanaTransactionKindEnum {
  solana = "SOLANA",
}
