/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdatePartialKmsAuthenticator
 */
export interface UpdatePartialKmsAuthenticator {
  /**
   * New name for the authenticator, if provided. If `None`, the name will not be updated.
   * @type {string}
   * @memberof UpdatePartialKmsAuthenticator
   */
  authenticatorName?: string | null;
  /**
   * New expiration time for the authenticator, if provided. If `None`, the description will not be updated.
   * @type {number}
   * @memberof UpdatePartialKmsAuthenticator
   */
  expiresInMs?: number | null;
}
