/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyConstant } from "./cel-policy-constant";
// May contain unused imports in some cases
// @ts-ignore
import type { CelPolicyRule } from "./cel-policy-rule";
// May contain unused imports in some cases
// @ts-ignore
import type { DerivationInfoSchema } from "./derivation-info-schema";
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationRootAccess } from "./organization-root-access";
// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationWalletScope } from "./organization-wallet-scope";
// May contain unused imports in some cases
// @ts-ignore
import type { UsdLimitSettings } from "./usd-limit-settings";
// May contain unused imports in some cases
// @ts-ignore
import type { VersionedOrganizationPolicyOneOf } from "./versioned-organization-policy-one-of";
// May contain unused imports in some cases
// @ts-ignore
import type { VersionedOrganizationPolicyOneOf1 } from "./versioned-organization-policy-one-of1";

/**
 * @type VersionedOrganizationPolicy
 * @export
 */
export type VersionedOrganizationPolicy = VersionedOrganizationPolicyOneOf | VersionedOrganizationPolicyOneOf1;
