/* tslint:disable */
/* eslint-disable */
/**
 * kms-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from "../base";
// @ts-ignore
import type { ErrorResponse } from "../model";
// @ts-ignore
import type { SimulateTransactionRequest } from "../model";
// @ts-ignore
import type { SimulationResult } from "../model";
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Simulate a transaction
     * @param {SimulateTransactionRequest} simulateTransactionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    simulateTransaction: async (
      simulateTransactionRequest: SimulateTransactionRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'simulateTransactionRequest' is not null or undefined
      assertParamExists("simulateTransaction", "simulateTransactionRequest", simulateTransactionRequest);
      const localVarPath = `/simulations`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(
        simulateTransactionRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Simulate a transaction
     * @param {SimulateTransactionRequest} simulateTransactionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async simulateTransaction(
      simulateTransactionRequest: SimulateTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SimulationResult>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.simulateTransaction(
        simulateTransactionRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["DefaultApi.simulateTransaction"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @summary Simulate a transaction
     * @param {SimulateTransactionRequest} simulateTransactionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    simulateTransaction(
      simulateTransactionRequest: SimulateTransactionRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<SimulationResult> {
      return localVarFp
        .simulateTransaction(simulateTransactionRequest, options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @summary Simulate a transaction
   * @param {SimulateTransactionRequest} simulateTransactionRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public simulateTransaction(simulateTransactionRequest: SimulateTransactionRequest, options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .simulateTransaction(simulateTransactionRequest, options)
      .then(request => request(this.axios, this.basePath));
  }
}
